### ISSUE TITLE
Mobile-Game Page

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#416] opened 2023-11-07 13:33 UTC
### Issue Description

I will create game page for mobile. 

### Deadline of the Issue

14.11.2023

### Reviewer

@haticerk

### Deadline for the Review

14.11.2023

**Comment by haticerk** [comment] 2023-11-22 14:13
The issue is resolved by merge.

**Closed by haticerk** 2023-11-22 14:13 UTC
Labels: type : development, priority : high, status : need_review, effort : high, team: mobile
