### ISSUE TITLE
Designing home page for mobile

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#274] opened 2023-10-17 13:41 UTC
### Issue Description

We will design a basic home page via benefiting from our Mock-ups that we prepared last year and we will implement home page of mobile app using Flutter.

### Tasks

Parts of the task:
- [x] Discuss and decide on possible design choices for home page of mobile app.
- [x] Implement home page of mobile app using Flutter.

### Extra Comments

None

### Final Step

None

### Deadline of the Issue

23.10.2023 - Monday - 23:59

### Reviewer

@haticerk

### Deadline for the Review

24.10.2023 - Tuesday - 16:00

**Comment by frknlke** [comment] 2023-10-22 16:12
We completed the implementation part of home page for our mobile app with my teammates, @haticerk , @kardelenerdal , and @senaal . We also pushed our current result to [a newly created branch](https://github.com/bounswe/bounswe2023group7/tree/feature/MB-274-initilaize-home-page/ludos/mobile) under mobile directory. Since we have some consistency issues with frontend team such as text format, font, page background colors etc. issue will be stay open for now. Also we have some minor work to complete before milestone. We assigned that works to mobile team members. After all todos completed, issue will be closed.

**Comment by senaal** [comment] 2023-10-22 21:59
I added some real posts and changed font colors.

**Comment by kardelenerdal** [comment] 2023-10-23 11:10
I updated our login and sign up page. The commit can be found [here](https://github.com/bounswe/bounswe2023group7/commit/05a494a54602d1b279e13a7af0cdf074d3a90588).

**Comment by frknlke** [comment] 2023-10-24 04:25
We also made a meeting with front end team to resolve incompatibilities. So the issue could be closed after review.

**Comment by haticerk** [comment] 2023-10-24 12:04
The issue is done. The branch is merged. I am closing the issue.

**Closed by haticerk** 2023-10-24 12:04 UTC
Labels: type : design, type : development, priority : high, status : need_review, effort : high, team: mobile
