### ISSUE TITLE
Bugfix: Like/Dislike Functionality

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2023group7#605] opened 2023-11-27 16:39 UTC
### Issue Description

There is a bug in like/dislike functions.

### Deadline of the Issue

27 November 2023 - Monday- 9pm

### Reviewer

@senaal 

### Deadline for the Review

27 November 2023 - Monday - 10pm

**Comment by haticerk** [comment] 2023-12-05 13:33
This bug still on. It needs to solve.

**Comment by haticerk** [comment] 2023-12-19 11:33
The issue is solved in #684. It can be reviewed.

**Comment by senaal** [comment] 2023-12-19 16:07
The issue is fixed, now I am closing the issue.

**Closed by senaal** 2023-12-19 16:07 UTC
Labels: priority : high, status : in_progress, effort : moderate
